input_data:
  file: "metrics_input/pipeline_reporting_metrics.csv"
  region_column: "territory_l4_name"

settings:
  visualization_type: "detailed"
  generate_ppt: true
  upload_to_drive: false
  drive_folder_id: null

metrics:
  cli_closed_pct:
    description: "Percentage of CLI that was Closed Lost"
    natural_name: "% CLI Closed Lost"
    dependencies: []
    hypothesis: ["sli_closed_won_pct", "CI_per_CLI", "CI_w_KI_pct"]
    higher_is_better: false
    
  cli_pitched_within_28d_pct:
    description: "Percentage of CLI pitched within 28 days"
    natural_name: "% CLI pitched within 28 days"
    dependencies: []
    hypothesis: ["CLI_per_active_AM", "CI_per_active_AM", "SLI_per_active_AM"]
    higher_is_better: true