# Hypothesis Scorer Configuration
# This file contains the configuration for metrics, hypotheses, and templates

# =================== CONFIGURATION GUIDE ===================
# scoring_method:                # Method to use for hypothesis scoring:
#                                    # - 'standard': Uses correlation, direction, and z-score
#                                    # - 'sign_based': Uses sign agreement, better for small sample sizes
# metrics:
#   <metric_column>:                 # Technical name of the metric column in the dataframe
#     name: <display_name>           # Human-readable name for display in visualizations
#     higher_is_better: true|false   # Whether higher values of this metric are considered positive
#     hypotheses:                    # List of hypotheses relevant to this metric
#       <hypothesis_column>:         # Technical name of the hypothesis column in the dataframe
#         name: <display_name>       # Human-readable name for display in visualizations
#         expected_direction:        # Expected relationship between metric and hypothesis:
#                                    # - 'same': Hypothesis and metric move in same direction
#                                    # - 'opposite': Hypothesis and metric move in opposite directions
#         template: <jinja_template> # Template text using Jinja2 syntax with {{ variable }} placeholders
#         summary_template: <jinja_template> # Template text using Jinja2 syntax with {{ variable }} placeholders. This is used for the summary slide in the PowerPoint presentation.
# =================== TEMPLATE VARIABLES ===================
# The following variables are available in templates:
# - region: Name of the anomalous region
# - metric_name: Name of the metric (uses the 'name' field above, not the column name)
# - metric_deviation: Magnitude of the deviation as a percentage
# - metric_dir: Direction of the deviation ('higher' or 'lower')
# - hypo_name: Name of the hypothesis (uses the 'name' field above, not the column name)
# - hypo_dir: Direction of the hypothesis value ('higher' or 'lower')
# - hypo_delta: Magnitude of the hypothesis deviation
# - ref_hypo_val: Reference (global) value of the hypothesis
# - score: Final score of the hypothesis
# - explained_ratio: Percentage of the metric deviation explained by the hypothesis
# ============================================================

scoring_method: "sign_based"  # Global scoring method for all metrics

metrics:
  conversion_rate_pct:
    name: "Conversion Rate"
    higher_is_better: true
    hypotheses:
      bounce_rate_pct:
        name: "Bounce Rate"
        expected_direction: "opposite"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than Global mean. This likely contributes to the {{ metric_dir }} overall performance.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} of {{ hypo_name }} than the global mean ({{ ref_hypo_val }}). Higher bounce rates typically result in lower conversion."
        summary_template: "TBA"
      page_load_time:
        name: "Page Load Time"
        expected_direction: "opposite"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than Global average.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} {{ hypo_name }} than the global average ({{ ref_hypo_val }}). Slower pages ({{ hypo_dir }} load times) typically result in {{ metric_dir }} conversion rates, explaining about {{ explained_ratio|int }}% of the observed difference."
        summary_template: "TBA"
      new_users_pct:
        name: "New User Percentage"
        expected_direction: "opposite"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than the global baseline.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} percentage of new users ({{ hypo_name }}) compared to the global average ({{ ref_hypo_val }}). New users typically convert at lower rates than returning users, which explains this pattern."
        summary_template: "TBA"

  avg_order_value:
    name: "Average Order Value"
    higher_is_better: true
    hypotheses:
      session_duration:
        name: "Session Duration"
        expected_direction: "same"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than the global average.\n\nRoot cause: {{ region }} shows {{ hypo_delta }} {{ hypo_dir }} {{ hypo_name }} compared to the global average ({{ ref_hypo_val }}). Users who spend more time browsing tend to make larger purchases, explaining about {{ explained_ratio|int }}% of the observed difference in order value."
        summary_template: "TBA"
      pages_per_session:
        name: "Pages per Session"
        expected_direction: "same"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than Global mean.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} {{ hypo_name }} than the global average ({{ ref_hypo_val }}). Users who view more pages typically explore more products, resulting in larger cart sizes and {{ hypo_dir }} order values."
        summary_template: "TBA"

  customer_satisfaction:
    name: "Customer Satisfaction"
    higher_is_better: true
    hypotheses:
      page_load_time:
        name: "Page Load Time"
        expected_direction: "opposite"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than global average.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} {{ hypo_name }} than the global average ({{ ref_hypo_val }}s). Slower page loading creates friction in the user experience, resulting in {{ metric_dir }} satisfaction scores."
        summary_template: "TBA"
      bounce_rate_pct:
        name: "Bounce Rate"
        expected_direction: "opposite"
        template: "{{ metric_name }} in {{ region }} is {{ metric_deviation }}% {{ metric_dir }} than Global benchmark.\n\nRoot cause: {{ region }} has {{ hypo_delta }} {{ hypo_dir }} {{ hypo_name }} than the global average ({{ ref_hypo_val }}). Higher bounce rates often indicate poor user experience or content mismatch, explaining the {{ metric_dir }} satisfaction scores." 
        summary_template: "TBA"