# Depth Analysis Configuration
# This file contains the configuration for depth analysis metrics and templates

# =================== CONFIGURATION GUIDE ===================
# metrics:
#   <metric_display_name>:           # Human-readable name of the metric (used internally)
#     technical_name: <tech_name>    # Technical column name in the DataFrame
#     type: rate|additive            # Type of metric:
#                                    # - 'rate': Metrics calculated as numerator/denominator (e.g., conversion rate)
#                                    # - 'additive': Metrics that are summed (e.g., revenue, orders)
#     numerator_col: <column_name>   # For rate metrics: column containing the numerator
#     denominator_col: <column_name> # For rate metrics: column containing the denominator
#     metric_col: <column_name>      # For additive metrics: column containing the metric values
#     template: <jinja_template>     # Template text using Jinja2 syntax with {{ variable }} placeholders
# =================== TEMPLATE VARIABLES ===================
# The following variables are available in templates:
# - metric_name: Display name of the metric (same as the key above)
# - anomalous_region: Name of the region being analyzed
# - row_rate: Rest-of-world rate (for rate metrics)
# - region_rate: Anomalous region rate (for rate metrics)
# - row_total: Rest-of-world total (for additive metrics)
# - region_total: Anomalous region total (for additive metrics)
# - delta: Gap between actual and expected performance
# - summary_table: Marker for where to insert the summary table
# Additional table markers can be used like {{ detail_table }}, {{ breakdown_table }}, etc.

# ============================================================

metrics:
  "Conversion Rate":
    technical_name: "conversion_rate_pct"
    type: "rate"
    numerator_col: "conversions"
    denominator_col: "visits"
    template: "{{ metric_name }} in {{ anomalous_region }} is {{ (region_rate*100)|round(1) }}% compared to {{ (row_rate*100)|round(1) }}% in the rest of world.\n\n{{ summary_table }}\n\nCoverage shows each sub-region's share of total volume. Contribution shows each sub-region's share of the performance gap."

  "Average Order Value":
    technical_name: "avg_order_value"
    type: "additive"
    metric_col: "revenue"
    template: "{{ metric_name }} in {{ anomalous_region }} totals {{ '{:,.0f}'.format(region_total) }} compared to {{ '{:,.0f}'.format(row_total) }} in the rest of world.\n\n{{ summary_table }}\n\nCoverage shows each sub-region's share of total volume. Contribution shows each sub-region's share of the performance gap."

  "Customer Satisfaction":
    technical_name: "customer_satisfaction"
    type: "rate"
    numerator_col: "sum_csat"
    denominator_col: "surveys"
    template: "{{ metric_name }} in {{ anomalous_region }} averages {{ region_rate|round(2) }} compared to {{ row_rate|round(2) }} in the rest of world.\n\n{{ summary_table }}\n\nCoverage shows each sub-region's share of total volume. Contribution shows each sub-region's share of the performance gap."

  "Revenue":
    technical_name: "revenue"
    type: "additive"
    metric_col: "revenue"
    template: "{{ metric_name }} in {{ anomalous_region }} totals {{ '{:,.0f}'.format(region_total) }} compared to {{ '{:,.0f}'.format(row_total) }} in the rest of world.\n\n{{ summary_table }}\n\nCoverage shows each sub-region's share of total volume. Contribution shows each sub-region's share of the performance gap." 